class_name ColorHelper
extends RefCounted

## This is a duplicate of core/math/color_names.inc named_colors (without _)
## Since those colors are only accessible through the Color constants
const named_colors := {
	"ALICEBLUE": null,
	"ANTIQUEWHITE": null,
	"AQUA": null,
	"AQUAMARINE": null,
	"AZURE": null,
	"BEIGE": null,
	"BISQUE": null,
	"BLACK": null,
	"BLANCHEDALMOND": null,
	"BLUE": null,
	"BLUEVIOLET": null,
	"BROWN": null,
	"BURLYWOOD": null,
	"CADETBLUE": null,
	"CHARTREUSE": null,
	"CHOCOLATE": null,
	"CORAL": null,
	"CORNFLOWERBLUE": null,
	"CORNSILK": null,
	"CRIMSON": null,
	"CYAN": null,
	"DARKBLUE": null,
	"DARKCYAN": null,
	"DARKGOLDENROD": null,
	"DARKGRAY": null,
	"DARKGREEN": null,
	"DARKKHAKI": null,
	"DARKMAGENTA": null,
	"DARKOLIVEGREEN": null,
	"DARKORANGE": null,
	"DARKORCHID": null,
	"DARKRED": null,
	"DARKSALMON": null,
	"DARKSEAGREEN": null,
	"DARKSLATEBLUE": null,
	"DARKSLATEGRAY": null,
	"DARKTURQUOISE": null,
	"DARKVIOLET": null,
	"DEEPPINK": null,
	"DEEPSKYBLUE": null,
	"DIMGRAY": null,
	"DODGERBLUE": null,
	"FIREBRICK": null,
	"FLORALWHITE": null,
	"FORESTGREEN": null,
	"FUCHSIA": null,
	"GAINSBORO": null,
	"GHOSTWHITE": null,
	"GOLD": null,
	"GOLDENROD": null,
	"GRAY": null,
	"GREEN": null,
	"GREENYELLOW": null,
	"HONEYDEW": null,
	"HOTPINK": null,
	"INDIANRED": null,
	"INDIGO": null,
	"IVORY": null,
	"KHAKI": null,
	"LAVENDER": null,
	"LAVENDERBLUSH": null,
	"LAWNGREEN": null,
	"LEMONCHIFFON": null,
	"LIGHTBLUE": null,
	"LIGHTCORAL": null,
	"LIGHTCYAN": null,
	"LIGHTGOLDENROD": null,
	"LIGHTGRAY": null,
	"LIGHTGREEN": null,
	"LIGHTPINK": null,
	"LIGHTSALMON": null,
	"LIGHTSEAGREEN": null,
	"LIGHTSKYBLUE": null,
	"LIGHTSLATEGRAY": null,
	"LIGHTSTEELBLUE": null,
	"LIGHTYELLOW": null,
	"LIME": null,
	"LIMEGREEN": null,
	"LINEN": null,
	"MAGENTA": null,
	"MAROON": null,
	"MEDIUMAQUAMARINE": null,
	"MEDIUMBLUE": null,
	"MEDIUMORCHID": null,
	"MEDIUMPURPLE": null,
	"MEDIUMSEAGREEN": null,
	"MEDIUMSLATEBLUE": null,
	"MEDIUMSPRINGGREEN": null,
	"MEDIUMTURQUOISE": null,
	"MEDIUMVIOLETRED": null,
	"MIDNIGHTBLUE": null,
	"MINTCREAM": null,
	"MISTYROSE": null,
	"MOCCASIN": null,
	"NAVAJOWHITE": null,
	"NAVYBLUE": null,
	"OLDLACE": null,
	"OLIVE": null,
	"OLIVEDRAB": null,
	"ORANGE": null,
	"ORANGERED": null,
	"ORCHID": null,
	"PALEGOLDENROD": null,
	"PALEGREEN": null,
	"PALETURQUOISE": null,
	"PALEVIOLETRED": null,
	"PAPAYAWHIP": null,
	"PEACHPUFF": null,
	"PERU": null,
	"PINK": null,
	"PLUM": null,
	"POWDERBLUE": null,
	"PURPLE": null,
	"REBECCAPURPLE": null,
	"RED": null,
	"ROSYBROWN": null,
	"ROYALBLUE": null,
	"SADDLEBROWN": null,
	"SALMON": null,
	"SANDYBROWN": null,
	"SEAGREEN": null,
	"SEASHELL": null,
	"SIENNA": null,
	"SILVER": null,
	"SKYBLUE": null,
	"SLATEBLUE": null,
	"SLATEGRAY": null,
	"SNOW": null,
	"SPRINGGREEN": null,
	"STEELBLUE": null,
	"TAN": null,
	"TEAL": null,
	"THISTLE": null,
	"TOMATO": null,
	"TRANSPARENT": null,
	"TURQUOISE": null,
	"VIOLET": null,
	"WEBGRAY": null,
	"WEBGREEN": null,
	"WEBMAROON": null,
	"WEBPURPLE": null,
	"WHEAT": null,
	"WHITE": null,
	"WHITESMOKE": null,
	"YELLOW": null,
	"YELLOWGREEN": null,
}


## Checks if a color is a named color.
## Based on Godot /core/math/color.cpp Color::find_named_color
static func is_named_color(name: String) -> bool:
	# Normalize name
	name = name.replace(" ", "")
	name = name.replace("-", "")
	name = name.replace("_", "")
	name = name.replace("'", "")
	name = name.replace(".", "")
	name = name.to_upper()

	return name in named_colors
